branch-defaults:
  main:
    environment: rails-eb-app-1-env
global:
  application_name: rails-eb-app-1
  branch: main
  default_ec2_keyname: aws-eb
  default_platform: Ruby 2.7 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
